[settings]
start = "20210101"
end = "20211231"
tzOffset = -7
skipChance = 0.1
weekendSkipChance = 0.6

[settings.author]
name = "Michelle Tilley"
email = "michelle@michelletilley.net"

[settings.range.normal]
min = 1
max = 50

[settings.range.weekend]
min = 1
max = 10

# Less computering over Christmas
[[overrides]]
  start = "20211220"
  end = "20211231"

  [overrides.settings.range.normal]
  min = 1
  max = 3

  [overrides.settings.range.weekend]
  min = 1
  max = 3

  [overrides.settings]
  skipChance = 0.95
  weekendSkipChance = 0.99

[[overrides]]
  start = "20211225"
  end = "20211225"

  [overrides.settings]
  skipChance = 1
  weekendSkipChance = 1
