[settings]
tzOffset = -7
skipChance = 0.1
weekendSkipChance = 0.6

[settings.author]
name = "Michelle Tilley"
email = "michelle@michelletilley.net"

[settings.range.normal]
min = 1
max = 50

[settings.range.weekend]
min = 1
max = 10

[[overrides]]
  start = "20190220"
  end = "20190228"

  [overrides.settings]
  skipChance = 0.9
  weekendSkipChance = 1

  [overrides.settings.range.normal]
  min = 1
  max = 3

  [overrides.settings.range.weekend]
  min = 1
  max = 3

[[overrides]]
  start = "20191220"
  end = "20191231"

  [overrides.settings.range.normal]
  min = 1
  max = 3

  [overrides.settings.range.weekend]
  min = 1
  max = 3

  [overrides.settings]
  skipChance = 0.95
  weekendSkipChance = 0.99

[[overrides]]
  start = "20181216"
  end = "20190106"

  [overrides.settings]
  skipChance = 1
  weekendSkipChance = 1

[[overrides]]
  start = "20190113"
  end = "20190120"

  [overrides.settings]
  skipChance = 1
  weekendSkipChance = 1
